- name : install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name : nginx
      state : present
  - name: Start nginx
    ansible.builtin.service:
      name : nginx
      state : started
  - name: enble nginx
    ansible.builtin.service:
      name : nginx
      state : got: enable